SELECT * FROM Customer
LIMIT 100;

--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,SUM(purchase_amount) AS Total_revenue
from Customer
Group by gender
Order by gender DESC;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT Customer_id ,purchase_amount
from Customer
Where discount_applied = 'Yes' AND purchase_amount >=(SELECT AVG(purchase_amount)from Customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, round(Avg(review_rating)::numeric,2) AS avg_review_rating
from Customer
Group by item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

--Q4)What is total revenue, total orders, and average order value (AOV)?

SELECT SUM(purchase_amount) AS Total_revenue,
       round(Avg(purchase_amount),2) AS avg_order_value,
       Count(*) AS Total_orders
from customer

--Q5)Which product categories generate the highest revenue and highest average order value?

--Highest Revenue
SELECT category,SUM(purchase_amount) AS Total_Revenue,
       round(Avg(purchase_amount),2) AS average_order_value,
        Count(*) AS Total_orders
FROM customer
GROUP BY category
ORDER BY Total_revenue DESC

--Average Order value

SELECT category,SUM(purchase_amount) AS Total_Revenue,
       round(Avg(purchase_amount),2) AS average_order_value,
        Count(*) AS Total_orders
FROM customer
GROUP BY category
ORDER BY average_order_value DESC

--Q6)How does revenue and spending behavior differ across customer segments (New, Returning, Loyal)?

--Checking Maximum and Minimum no. of Previous purchases

SELECT previous_purchases ,COUNT(*)
FROM customer
GROUP BY previous_purchases
ORDER BY previous_purchases DESC;

--Checking how many new customers are there 

SELECT COUNT(*) 
FROM customer
WHERE previous_purchases = 0;

--Creating Segmentations and checking the revenue and Spending behaviour among the returning customers
--as New customers is 0 

SELECT 
  CASE WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning'
       WHEN previous_purchases BETWEEN 16 AND 30 THEN 'Frequent_buyers'
	   ELSE 'Loyal'
 END AS Customer_Segments,
SUM(purchase_amount) AS Total_Revenue,
round(Avg(purchase_amount),2) AS average_order_value,
COUNT(*) AS Total_customers,
ROUND( SUM(purchase_amount) * 100.0 /
        (SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_percentage

FROM customer
GROUP BY Customer_Segments
ORDER BY Total_Revenue DESC;

--Q7)Does customer loyalty correlate with subscription adoption?

SELECT  CASE WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning'
       WHEN previous_purchases BETWEEN 16 AND 30 THEN 'Frequent_buyers'
	   ELSE 'Loyal'
 END AS Customer_Segments,
 COUNT(*) AS Total_customers,
 SUM(CASE WHEN subscription_status ='Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
 ROUND(SUM(CASE WHEN subscription_status ='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS subscribed_p

 from customer
 GROUP BY Customer_Segments
ORDER BY subscribed_p DESC;

--Q8)How does discounting impact revenue performance and customer spending behavior?

SELECT discount_applied, round(Avg(purchase_amount),2) AS avg_order_value,
       COUNT(*) AS Total_customers,SUM(purchase_amount) AS Total_revenue,
	   Round(SUM(purchase_amount) *100.0/(SELECT SUM(purchase_amount)FROM customer),2) AS Revenue_p
FROM customer
GROUP BY discount_applied
ORDER BY Total_Revenue DESC;

--Q9)Are loyal customers more price-sensitive than returning customers?(i.e., are they more likely to use discounts?)

SELECT  CASE WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning'
       WHEN previous_purchases BETWEEN 16 AND 30 THEN 'Frequent_buyers'
	   ELSE 'Loyal'
 END AS Customer_Segments,
 COUNT(*) AS Total_customers,
SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END) AS discount_users,
ROUND(SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS discount_usage_percentage

FROM customer
GROUP BY Customer_Segments
ORDER BY discount_usage_percentage DESC;

--Q10)Who are the top 10% highest spending customers, and how much revenue do they contribute?

WITH ranked_customers AS (
 SELECT customer_id,
       purchase_amount,
NTILE(10)OVER(ORDER BY purchase_amount DESC) AS  revenue_decile
FROM customer)

SELECT SUM(purchase_amount) AS Top_10_revenue,
       ROUND(SUM(purchase_amount)*100.0/(SELECT SUM(purchase_amount)FROM customer),2) AS revenue_percent
	   FROM ranked_customers
	   WHERE revenue_decile=1;

--Q11)What are the top 3 highest revenue-generating products within each category?

WITH product_ranking  AS (
          SELECT  SUM(purchase_amount)AS Total_revenue,
          category,item_purchased,
		  ROW_NUMBER()OVER(PARTITION BY category ORDER BY SUM(purchase_amount) DESC) AS rank_in_category
		  FROM customer
		  GROUP BY category,item_purchased
)

SELECT * FROM product_ranking
WHERE rank_in_category <=3;

--Q12)As customers are ranked from highest to lowest spenders, how quickly does revenue accumulate?
--Do the top customers drive a disproportionate share of revenue?

WITH revenue_ranked AS(
SELECT customer_id, purchase_amount,
       ROW_NUMBER()OVER(ORDER BY purchase_amount DESC) AS revenue_rank,
      SUM(purchase_amount)OVER(ORDER BY purchase_amount DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) 
	  AS cumulative_revenue
FROM customer
)
SELECT customer_id, purchase_amount,revenue_rank,cumulative_revenue,
       ROUND(cumulative_revenue * 100.0/(SELECT SUM(purchase_amount) FROM customer),2)
AS cumulative_revenue_percent
FROM revenue_ranked;

--Q13)What is the revenue contribution of each age group?

SELECT 
   age_group,
COUNT(*) AS Total_customers,
SUM(purchase_amount) AS Total_revenue,
ROUND(AVG(purchase_amount),2) AS avg_order_value,
ROUND(SUM(purchase_amount)*100.0/(SELECT SUM(purchase_amount) FROM customer),2) AS revenue_percent
FROM customer
GROUP BY age_group
ORDER BY Total_revenue DESC
